CREATE TABLE "agro-scrap_offer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agro-scrap_offer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"cereal_type" text NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"quantity" text NOT NULL,
	"region" text NOT NULL,
	"contact" text NOT NULL,
	"source" text NOT NULL,
	"scraped_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agro-scrap_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agro-scrap_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "offer_cereal_type_idx" ON "agro-scrap_offer" USING btree ("cereal_type");--> statement-breakpoint
CREATE INDEX "offer_price_idx" ON "agro-scrap_offer" USING btree ("price");--> statement-breakpoint
CREATE INDEX "offer_scraped_at_idx" ON "agro-scrap_offer" USING btree ("scraped_at");--> statement-breakpoint
CREATE INDEX "name_idx" ON "agro-scrap_post" USING btree ("name");